### ISSUE TITLE
增加多网卡小lantency功能

### ISSUE THREAD

**Issue by happilying** [Mmx233/BitSrunLoginGo#37]
RT，两次认证时间间隔要大于三秒…

**Comment by Mmx233** [comment]
wait for this be released: https://github.com/Mmx233/BackoffCli

**Comment by Mmx233** [comment]
目前发布的版本是带有认证间隔的，默认为五分钟

```yaml
settings:
    guardian:
        duration: 300
```
